include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - combinators_ordering
    - comment_references
    - invalid_case_patterns
    - library_annotations
    - one_member_abstracts
    - only_throw_errors
    - prefer_relative_imports
    - avoid_print
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_final_fields
    - use_key_in_widget_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - package_api_docs

analyzer:
  errors:
    package_api_docs: error
    prefer_relative_imports: error
    missing_return: error
    unused_element: error
    unused_import: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    sort_unnamed_constructors_first: error
    sort_pub_dependencies: error
    unnecessary_statements: error
  plugins:
    - custom_lint

custom_lint:
  enable_all_lint_rules: true
