name: healpen
description: This app is derived for my thesis.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.1
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  firebase_analytics: ^10.4.3
  firebase_app_check: ^0.1.4+3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_dynamic_links: ^5.3.3
  firebase_ui_auth: ^1.5.0
  firebase_ui_oauth_apple: ^1.2.4
  firebase_ui_oauth_google: ^1.2.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_riverpod: ^2.1.3
  flutter_screwdriver: ^3.0.0
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.1
  http: ^0.13.5
  json_annotation: ^4.8.0
  responsive_sizer: ^3.1.1
  rive: ^0.11.4
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.2.0
  simple_gesture_detector: ^0.2.0
  sprung: ^3.0.1
  validated: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  lint: ^2.1.2
  riverpod_lint: ^1.2.0

flutter:
  uses-material-design: true
