name: healpen
description: This app is derived for my thesis.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_snack_bar: ^0.4.0
  auto_animated: ^3.2.0
  cloud_firestore: ^4.8.1
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.3
  envied: ^0.5.2
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_pagination: ^3.0.1
  firebase_storage: ^11.2.6
  firebase_ui_auth: ^1.5.0
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_iterum: ^0.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.1.3
  flutter_screwdriver: ^3.0.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.3.0
  github: ^9.17.0
  google_fonts: ^6.1.0
  googleapis: ^13.0.0
  googleapis_auth: ^1.4.1
  graphic: ^2.2.1
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  json_annotation: ^4.8.0
  keyboard_detection: ^0.7.0
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  responsive_sizer: ^3.1.1
  restart_app: ^1.2.1
  rive: ^0.13.0
  salomon_bottom_bar: ^3.3.1
  simple_gesture_detector: ^0.2.0
  smooth_page_indicator: ^1.1.0
  sprung: ^3.0.1
  syncfusion_flutter_calendar: ^24.2.9
  syncfusion_flutter_charts: ^24.2.9
  url_launcher: ^6.2.1
  validated: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.6.2
  envied_generator: ^0.5.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  lint: ^2.1.2
  riverpod_lint: ^2.0.1

flutter:
  assets:
    - shorebird.yaml
    - assets/images/onboarding/welcome.svg
    - assets/images/onboarding/journal.svg
    - assets/images/onboarding/insights.svg
    - assets/images/onboarding/begin.svg
    - assets/rive/emotional_echo.riv
    - assets/icon/brain-2x.png
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon-2x.png"
  min_sdk_android: 29
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
