name: healpen
description: This app is derived for my thesis.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  carousel_slider: ^4.2.1
  colorful_safe_area: ^1.0.0
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.5.4
  expandable_page_view: ^1.0.17
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  firebase_performance: ^0.9.0+10
  flash: ^3.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_custom_license_page: ^0.0.3
  flutter_launcher_icons: ^0.13.0
  flutter_riverpod: ^2.1.3
  flutter_screwdriver: ^2.1.0
  flutter_secure_storage: ^8.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_web_auth_2: ^2.1.2
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.1
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  page_transition: ^2.0.9
  provider: ^6.0.5
  rename: ^2.1.1
  responsive_sizer: ^3.1.1
  rive: ^0.10.1
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  simple_gesture_detector: ^0.2.0
  sprung: ^3.0.1
  syncfusion_flutter_charts: ^21.1.37
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.2

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  lint: ^1.10.0
  riverpod_lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/cricket.riv
    - assets/rive/code_time.riv
