// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ5gsnkRQdWK7kEpl3BBzfsSCEIyBfTsc',
    appId: '1:1058887275393:android:c19882059cad1bbbeb0e80',
    messagingSenderId: '1058887275393',
    projectId: 'healpen',
    storageBucket: 'healpen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsYSx3Q0xNnrYPJnINrfRmeCOQ48BcmPI',
    appId: '1:1058887275393:ios:8448617507911eceeb0e80',
    messagingSenderId: '1058887275393',
    projectId: 'healpen',
    storageBucket: 'healpen.appspot.com',
    androidClientId:
        '1058887275393-tb4beba658al39ttq75gnc8g3mvi7e79.apps.googleusercontent.com',
    iosClientId:
        '1058887275393-etpmst24vst3vcfpalvo83k4j43igbh2.apps.googleusercontent.com',
    iosBundleId: 'com.mikezamayias.healpen',
  );
}
