name: Notion update workflow
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get commits and update Notion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          pip install requests
          python -c "
          import os
          import requests
          from datetime import datetime, timedelta

          GITHUB_API_URL = 'https://api.github.com'
          NOTION_API_URL = 'https://api.notion.com/v1'

          GITHUB_REPOSITORY = os.getenv('GITHUB_REPOSITORY')
          DATABASE_ID = os.getenv('NOTION_DATABASE_ID')
          GITHUB_TOKEN = os.getenv('GITHUB_TOKEN')
          NOTION_TOKEN = os.getenv('NOTION_TOKEN')

          yesterday = datetime.now() - timedelta(1)
          since = yesterday.strftime('%Y-%m-%dT%H:%M:%SZ')

          github_headers = {'Authorization': f'token {GITHUB_TOKEN}'}
          notion_headers = {
              'Authorization': f'Bearer {NOTION_TOKEN}',
              'Notion-Version': '2021-08-16',
              'Content-Type': 'application/json'
          }

          response = requests.get(
              f'{GITHUB_API_URL}/repos/{GITHUB_REPOSITORY}/commits?since={since}', 
              headers=github_headers
          )

          commits = response.json()

          for commit in commits:
              message = commit['commit']['message']

              data = {
                  'parent': {'database_id': DATABASE_ID},
                  'properties': {
                      'Name': {'title': [{'text': {'content': message}}]},
                      'Date': {'date': {'start': commit['commit']['author']['date']}}
                  }
              }

              response = requests.post(
                  f'{NOTION_API_URL}/pages', 
                  headers=notion_headers, 
                  json=data
              )
          "
